### PR TITLE
GPII-3479: Updated Morphic logos

### PR DESCRIPTION
**Pull request by javihernandez**

### CODE REVIEW

**Comment by javihernandez** [comment]
@danailbd Bern told me that these files needed to be updated because there was a problem with the fonts.
Now they are in sync with what it's in the Google Drive folders.

**Comment by danailbd** [comment]
Merging it.
Probably not related to this change but I should note that the tooltip icon differs quite a bit from the one that is displayed in the tooltip:
virtualbox_gpii-app_default_1535475662352_85652_30_10_2018_23_39_13

**Comment by javihernandez** [comment]
@danailbd thanks for merging. Regarding the tooltip icon, you're right, I've seen that we are using "TaskTrayIcon_outline.svg" but can't find an updated version of it in the google drive folder. Where is this svg coming from? Is this something we should ask Bern about?

**Comment by danailbd** [comment]
Yes, from what I see Bern has provided us with that `svg` so I'll let him know about this difference. Looks like something minor to be fixed...

**Pull request merged**
